ktor:
  application:
    modules:
      - com.lilac.identity.ApplicationKt.module
  deployment:
    port: 8080
  development: true
jwt:
  domain: "http://localhost:8080/"
  issuer: "lilac-identity"
  audience: "lilac-identity"
  realm: "Lilac Identity"
  algorithm: "HS256"
  accessTokenExpInMins: 15
  refreshTokenExpInDays: 30
  emailVerificationExpInMins: 10
  resetPasswordExpInMins: 10

  secret: ${JWT_SECRET}

postgres:
  url: ${DATABASE_URL}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD} # Usually SMTP Key
  from: ${MAIL_FROM}