ktor:
  application:
    modules:
      - com.lilac.identity.ApplicationKt.module
  deployment:
    port: ${PORT}
  development: ${DEVELOPMENT}
  domain: ${DOMAIN}

auth:
  realm: "Lilac Identity"
  privateKeyPath: ${PRIVATE_KEY_PATH}
  audience: "lilac-identity"
  issuer: "lilac-identity"
  accessTokenExpInMins: 15
  refreshTokenExpInDays: 30

verification:
  realm: "Lilac Identity"
  secret: ${VERIFICATION_SECRET}
  audience: "lilac-identity"
  issuer: "lilac-identity"
  emailVerificationTokenExpInMins: 10
  resetPasswordTokenExpInMins: 10
  hashSecret: ${VERIFICATION_HASH_SECRET}

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD} # Usually SMTP Key
  from: ${MAIL_FROM}

postgres:
  url: ${DATABASE_URL}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  maximumPoolSize: 10